matrix:
  include:
  - os: linux
    dist: xenial
    language: csharp
    dotnet: 2.2.203
    mono: none
    services: [docker]
    addons:
      apt:
        packages:
        - libxml2-utils
        - powershell
        sources:
        - sourceline: deb [arch=amd64] https://packages.microsoft.com/ubuntu/16.04/prod xenial main
          key_url: https://packages.microsoft.com/keys/microsoft.asc
    cache:
      directories:
      - $HOME/.nuget/packages
      - $HOME/.local/share/NuGet/v3-cache
  - os: osx
    osx_image: xcode10.1
    language: csharp
    dotnet: 2.2.203
    mono: none
    cache:
      directories:
      - $HOME/Library/Caches/Homebrew
      - $HOME/.nuget/packages
      - $HOME/.local/share/NuGet/v3-cache
  - os: windows
    language: shell
    cache:
      directories:
      - $HOME/.nuget/packages
      - $HOME/AppData/Local/NuGet/v3-cache
      - $HOME/.ChocoCache
    filter_secrets: false  # https://travis-ci.community/t/current-known-issues-please-read-this-before-posting-a-new-topic/264/10

solution: Libplanet.sln
install:
- |
  set -ev
  if [[ "$TRAVIS_OS_NAME" = "windows" ]]; then
    choco config set cacheLocation "$(cygpath -w "$HOME/.ChocoCache")"

    # .NET Core SDK 2.2+
    choco install dotnetcore-sdk
    dotnet --info
  fi
  set +ev

# Restore NuGet packages (dependencies)
- |
  for i in 1 2 3; do
    # Retry up to 3 times
    dotnet restore -s https://api.nuget.org/v3/index.json && break
  done

script:
# Fail fast if anything in below commands fails
- set -e

# Check coding styles
- hooks/check-bom

# Build the whole solution
- dotnet build -c Release

# Run unit tests (without TURN server)
- dotnet test -c Release -v n --filter "RequireTurnServer!=true"
# FIXME: For unknown reason, on Travis CI tests depending on TURN_SERVER_URL
#        seems not terminated or to take too long time.  We should diagnose
#        this and make the CI to run these tests too.

# Turn off "set -e" option
- set +e

before_cache:
- |
  if [[ "$TRAVIS_OS_NAME" = "osx" ]]; then
    brew cleanup
  fi
