pool:
  vmImage: 'VS2017-Win2016'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@0
- task: DotNetCoreCLI@2
  displayName: 'Restore'
  inputs:
    command: 'restore'
- task: VSBuild@1
  displayName: 'Build'
  inputs:
    solution: '**/*.sln'
    vsVersion: latest
    platform: 'any cpu'
    configuration: release
    logProjectEvents: true
- task: VSTest@2
  displayName: 'Test'
  inputs:
    vsVersion: latest
    platform: 'any cpu'
    configuration: release
