parameters:
  configuration: Debug
  testArguments: ""

steps:

- task: Bash@3
  displayName: hooks/check-bom
  inputs:
    targetType: filePath
    filePath: hooks/check-bom

- task: NuGetCommand@2
  displayName: nuget install xunit.runner.console
  inputs:
    command: custom
    arguments: install xunit.runner.console

- task: CmdLine@2
  displayName: msbuild /restore
  inputs:
    script: |
      msbuild \
        /restore \
        /p:Configuration=${{ parameters.configuration }}

- task: CmdLine@2
  displayName: xunit.console.exe *.Tests.dll
  inputs:
    script: |
      mono xunit.runner.console.*/tools/net472/xunit.console.exe \
        *.Tests/bin/${{ parameters.configuration }}/net*/*.Tests.dll
  env:
    TURN_SERVER_URL: ${{ parameters.turnServerUrl }}
  timeoutInMinutes: 10
