on:
  push: []
  schedule:
  - cron: 59 14 * * *
name: main

jobs:
  build:
    name: dist
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - uses: dahlia/actions/checkout-pull-request@master
    - run: .github/bin/dist-version.ps1
      shell: pwsh
    - run: .github/bin/dist-release-note.sh CHANGES.md obj/release_note.txt
    - uses: actions/upload-artifact@master
      with:
        name: dist-obj
        path: obj/
    - run: .github/bin/dist-pack.sh
    - uses: actions/upload-artifact@master
      with:
        name: dist-bin
        path: Libplanet/bin/Release/
    - if: >-
        github.event_name != 'pull_request' &&
        startsWith(github.ref, 'refs/tags/')
      run: .github/bin/dist-github-release.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - if: >-
        github.event_name != 'pull_request' &&
        startsWith(github.ref, 'refs/tags/')
      run: .github/bin/dist-nuget.sh
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}

  docs:
    name: docs
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - uses: dahlia/actions/checkout-pull-request@master
    - run: mkdir -p Docs/obj/
    - uses: dahlia/actions/docfx@master
      env:
        MSBUILD_PROJECT: Libplanet
      with:
        args: Docs/docfx.json
    - uses: actions/upload-artifact@master
      with:
        name: docs
        path: Docs/_site/
    - run: Docs/publish.sh
      env:
        GHPAGES_SSH_KEY: ${{ secrets.GHPAGES_SSH_KEY }}
    - uses: shawnbot/action-status@master
      env:
        GH_CHECK_STATUS_TOKEN: ${{ secrets.GH_CHECK_STATUS_TOKEN }}
      with:
        args: >-
          --repository="${{ github.repository }}"
          --sha="${{ github.sha }}"
          --context=docs
          --description='Libplanet docs generated by DocFX'
          --state=success
          --url="$(cat Docs/obj/url.txt)"
          --token="$GH_CHECK_STATUS_TOKEN"
